"""schema updates for profile

Revision ID: 357944c597e2
Revises: 
Create Date: 2022-05-17 12:40:46.346036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357944c597e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_first_name_key', 'users', type_='unique')
    op.drop_constraint('users_last_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_last_name_key', 'users', ['last_name'])
    op.create_unique_constraint('users_first_name_key', 'users', ['first_name'])
    # ### end Alembic commands ###
